//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotedRedZones
    {
        public int AllotmentID { get; set; }
        public Nullable<int> RedZoneID_FK { get; set; }
        public Nullable<int> DetailID_FK { get; set; }
    
        public virtual MobDetail MobDetail { get; set; }
        public virtual RedZone RedZone { get; set; }
    }
}
