//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barrier
    {
        public int BarrierID { get; set; }
        public Nullable<int> MobID_FK { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<double> BarrierLat { get; set; }
        public Nullable<double> BarrierLon { get; set; }
    
        public virtual Mob Mob { get; set; }
    }
}
