<<<<<<< HEAD
<<<<<<< HEAD
﻿
=======
=======
>>>>>>> parent of d95e63f (deleted-db-entities)
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
>>>>>>> parent of d95e63f (deleted-db-entities)
=======
>>>>>>> parent of d95e63f (deleted-db-entities)
