//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobDetail()
        {
            this.AllotedRedZones = new HashSet<AllotedRedZones>();
            this.MobTimeline = new HashSet<MobTimeline>();
        }
    
        public int DetailID { get; set; }
        public Nullable<int> MobID_FK { get; set; }
        public Nullable<int> DroneID_FK { get; set; }
        public Nullable<int> UsersID_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllotedRedZones> AllotedRedZones { get; set; }
        public virtual Drone Drone { get; set; }
        public virtual Mob Mob { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobTimeline> MobTimeline { get; set; }
    }
}
