//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobOfficer
    {
        public int moId { get; set; }
        public Nullable<int> UserId_FK { get; set; }
        public Nullable<int> MobId_FK { get; set; }
    
        public virtual Mob Mob { get; set; }
        public virtual User User { get; set; }
    }
}
