//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobTimeline
    {
        public int TimelineID { get; set; }
        public Nullable<int> MobStrength { get; set; }
        public Nullable<double> TimelineLon { get; set; }
        public Nullable<double> TimelineLat { get; set; }
        public Nullable<System.DateTime> TimelineDate { get; set; }
        public Nullable<System.TimeSpan> TimelineTime { get; set; }
        public Nullable<int> MobID_FK { get; set; }
        public Nullable<int> DroneID_FK { get; set; }
    
        public virtual Mob Mob { get; set; }
    }
}
