//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mob_monitoring_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VidID { get; set; }
        public Nullable<int> MobID_FK { get; set; }
        public Nullable<System.DateTime> VidDate { get; set; }
        public Nullable<System.TimeSpan> VidStartTime { get; set; }
        public Nullable<System.TimeSpan> VidEndTime { get; set; }
        public string VidPath { get; set; }
        public Nullable<int> DroneID_FK { get; set; }
    
        public virtual Drone Drone { get; set; }
        public virtual Mob Mob { get; set; }
    }
}
